-- ====================================================================
-- Migration: Create public.notifications with RLS and mark read RPC
-- File:     20251016_create_notifications.sql
-- Purpose:  Robust notifications table for app events + secure RLS
-- Author:   Migration generated by tooling (2025-10-16)
-- ====================================================================

-- Ensure UUID generator is available
create extension if not exists pgcrypto;

-- 1) Table: public.notifications
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  type text not null check (
    type in (
      'friend_request',
      'friend_update',
      'achievement',
      'game_invite',
      'booking_confirmation',
      'booking_reminder',
      'general_update',
      'system_alert',
      'game_update'
    )
  ),
  title text not null,
  message text not null,
  action_route text null,
  data jsonb not null default '{}'::jsonb,
  is_read boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

-- Comments for clarity
comment on table public.notifications is 'User-targeted app notifications with strict RLS; client reads and marks read via RPC.';
comment on column public.notifications.id is 'Primary key (UUID).';
comment on column public.notifications.user_id is 'Recipient user id; FK to public.users(id).';
comment on column public.notifications.type is 'Notification category; constrained to known types.';
comment on column public.notifications.title is 'Short, human-readable title shown in UI.';
comment on column public.notifications.message is 'Message body content shown in UI.';
comment on column public.notifications.action_route is 'Optional app route to navigate (e.g., /friends or /game-detail/FRI7V7).';
comment on column public.notifications.data is 'Arbitrary metadata for the client; JSONB payload.';
comment on column public.notifications.is_read is 'Read flag; defaults to false and set true when viewed.';
comment on column public.notifications.created_at is 'Creation timestamp in UTC.';

-- Indexes
create index if not exists idx_notifications_user_created_at
  on public.notifications (user_id, created_at desc);

create index if not exists idx_notifications_read_user
  on public.notifications (is_read, user_id);

-- Enable RLS
alter table public.notifications enable row level security;

-- Policies
-- SELECT: Only the owner can read their notifications
create policy if not exists "Users can read their notifications"
  on public.notifications
  for select to authenticated
  using (auth.uid() = user_id);

-- UPDATE (mark as read): Only the owner can update their rows
create policy if not exists "Users can mark their notifications read"
  on public.notifications
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Note: No INSERT/DELETE policies are created for clients.
-- Writes are expected via SECURITY DEFINER functions only.

-- 2) Helper RPC: mark_notification_read
-- Returns the updated row after setting is_read = true.
create or replace function public.mark_notification_read(
  p_user_id uuid,
  p_notification_id uuid
)
returns public.notifications
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.notifications;
begin
  -- Ensure the caller''s auth context matches the provided user id
  if p_user_id is distinct from auth.uid() then
    raise exception 'Unauthorized: p_user_id must equal auth.uid()'
      using errcode = '42501'; -- insufficient_privilege
  end if;

  update public.notifications
     set is_read = true
   where id = p_notification_id
     and user_id = p_user_id
  returning * into v_row;

  if not found then
    raise exception 'Notification not found or not owned by user'
      using errcode = 'P0002'; -- no_data_found
  end if;

  return v_row;
end;
$$;

comment on function public.mark_notification_read(uuid, uuid) is
  'Marks a notification as read for the authenticated user and returns the updated row. SECURITY DEFINER with user-id check.';

-- Optional: grant execute to authenticated users
grant execute on function public.mark_notification_read(uuid, uuid) to authenticated;

-- End of migration
